### ISSUE TITLE
Error installing on windows 10 ?

### ISSUE THREAD

**Issue by StefH** [carsenk/explorer#30]
When doing an install : `C:\Users\Stef\Documents\__TEST__\explorer>npm i`, I get this error:

> > bufferutil@1.3.0 install C:\Users\Stef\Documents\__TEST__\explorer\node_modules\bufferutil
> > node-gyp rebuild
> 
> 
> C:\Users\Stef\Documents\__TEST__\explorer\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
> gyp ERR! configure error
> gyp ERR! stack Error: Can't find Python executable "C:\Users\Stef\AppData\Local\Programs\Python\Python36-32\python.EXE", you can set the PYTHON env variable.
> gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
> gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
> gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
> gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
> gyp ERR! System Windows_NT 10.0.16299
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\Users\Stef\Documents\__TEST__\explorer\node_modules\bufferutil
> gyp ERR! node -v v8.9.3
> gyp ERR! node-gyp -v v3.6.2
> gyp ERR! not ok
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! bufferutil@1.3.0 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the bufferutil@1.3.0 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Stef\AppData\Roaming\npm-cache\_logs\2017-12-08T20_17_42_112Z-debug.log
> 

Python is installed:

> C:\Users\Stef\Documents\__TEST__\explorer>python
> Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 17:26:49) [MSC v.1900 32 bit (Intel)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>> quit
> Use quit() or Ctrl-Z plus Return to exit
> >>> ^Z

**Comment by Feliphegomez** [comment]
It should install **Python** and others files.

**Run** this in Windows **PowerShell** as **administrator:**

~~~sh
npm install --global --production windows-build-tools
~~~
