### ISSUE TITLE
TypeError: The header content contains invalid characters

### ISSUE THREAD

**Issue by lieyanboy** [carsenk/explorer#45]
Starting up http-server, serving ./app on port: 8000
Hit CTRL-C to stop the server
[Wed, 11 Apr 2018 08:44:37 GMT] "GET /" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36"
_http_outgoing.js:497
    throw new TypeError('The header content contains invalid characters');
    ^

TypeError: The header content contains invalid characters
    at validateHeader (_http_outgoing.js:497:11)
    at ServerResponse.setHeader (_http_outgoing.js:501:3)
    at module.exports.ResponseStream.(anonymous function) [as setHeader] (D:\FilesCache\gits\explorer\node_modules\union\lib\response-stream.js:86:34)
    at serve (D:\FilesCache\gits\explorer\node_modules\ecstatic\lib\ecstatic.js:146:11)
    at D:\FilesCache\gits\explorer\node_modules\ecstatic\lib\ecstatic.js:139:9
    at FSReqWrap.oncomplete (fs.js:153:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! EthereumExplorerV2@0.1.0 start: `http-server ./app -a localhost -p 8000 -c-1`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the EthereumExplorerV2@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Program Files\nodejs\node_cache\_logs\2018-04-11T08_44_38_000Z-debug.log

**Comment by Hamdi-G** [comment]
`npm install -g http-server` should fix the problem :)

**Comment by peer2peer** [comment]
How about this issue? No fix? I met this issue too.
