### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by eljeffeg** [carsenk/explorer#64]
Have been trying to install this without luck.  The original version of explorer seems to have the same issue but continues and starts the server and appears to work.  I've tried my best to fix node-gyp rebuild, but can't seem to create the binding.gyp, even after reinstalling bcrypt.  Not sure what the issue is, but thought I would report it as I've spent 2 hours trying to get it to work.
```
make: Leaving directory '/home/kali/explorer/node_modules/bufferutil/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/nodejs/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.4.0-kali3-amd64
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/kali/explorer/node_modules/bufferutil
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bufferutil@1.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bufferutil@1.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kali/.npm/_logs/2020-04-26T16_27_25_331Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! EthereumExplorerV2@0.1.0 prestart: `npm install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the EthereumExplorerV2@0.1.0 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kali/.npm/_logs/2020-04-26T16_27_25_378Z-debug.log
```

**Comment by tomafc330** [comment]
You need to use node ver 6.1.0 for this. To do so without overridding your global node version, use `nave`
<install nave>
nave use 6.1.0
npm install

**Comment by dipanjan** [comment]
Doesn't work for me. I get the following error:

```
$ node --version
v6.1.0

$ npm --version
3.8.6

$ npm install                                
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142 
npm WARN deprecated har-validator@5.1.5: this library is no longer supported                                        
npm WARN deprecated bower@1.8.8: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/                                                                                       
npm WARN deprecated ecstatic@0.4.13: https://github.com/jfhbrook/node-ecstatic/issues/259                           
npm WARN deprecated mkdirp@0.0.7: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)                           
npm WARN deprecated chokidar@1.7.0: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.                                                                                   
npm WARN deprecated connect@2.30.2: connect 2.x series is deprecated                                                
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue        
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm ERR! Linux 4.15.0-118-generic
npm ERR! argv "/home/myuser/.nave/installed/6.1.0/bin/node" "/home/myuser/.nave/installed/6.1.0/bin/npm" "install"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/home/myuser/.nave/installed/6.1.0/lib/node_modules/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/home/myuser/.nave/installed/6.1.0/lib/node_modules/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/home/myuser/.nave/installed/6.1.0/lib/node_modules/npm/lib/install/deps.js:455:12)
npm ERR! typeerror     at /home/myuser/.nave/installed/6.1.0/lib/node_modules/npm/lib/install/deps.js:456:7
npm ERR! typeerror     at /home/myuser/.nave/installed/6.1.0/lib/node_modules/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /home/myuser/.nave/installed/6.1.0/lib/node_modules/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/home/myuser/.nave/installed/6.1.0/lib/node_modules/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/home/myuser/.nave/installed/6.1.0/lib/node_modules/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/home/myuser/.nave/installed/6.1.0/lib/node_modules/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /home/myuser/.nave/installed/6.1.0/lib/node_modules/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
npm ERR! Linux 4.15.0-118-generic
npm ERR! argv "/home/myuser/.nave/installed/6.1.0/bin/node" "/home/myuser/.nave/installed/6.1.0/bin/npm" "install"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/home/myuser/.nave/installed/6.1.0/lib/node_modules/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/home/myuser/.nave/installed/6.1.0/lib/node_modules/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/home/myuser/.nave/installed/6.1.0/lib/node_modules/npm/lib/install/deps.js:455:12)
npm ERR! typeerror     at /home/myuser/.nave/installed/6.1.0/lib/node_modules/npm/lib/install/deps.js:456:7
npm ERR! typeerror     at /home/myuser/.nave/installed/6.1.0/lib/node_modules/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /home/myuser/.nave/installed/6.1.0/lib/node_modules/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/home/myuser/.nave/installed/6.1.0/lib/node_modules/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/home/myuser/.nave/installed/6.1.0/lib/node_modules/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/home/myuser/.nave/installed/6.1.0/lib/node_modules/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /home/myuser/.nave/installed/6.1.0/lib/node_modules/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
```

**Comment by followinds** [comment]
i have   the  same err too !!!   i cant run it.   my node version is  6.1.0 ,but its  no use.@tomafc330 


npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/local/lib/node_modules/npm/lib/install/deps.js:455:12)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/lib/install/deps.js:456:7
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
npm ERR! Linux 5.4.0-42-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/local/lib/node_modules/npm/lib/install/deps.js:455:12)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/lib/install/deps.js:456:7
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ch/work/explorer/npm-debug.log

**Comment by pouyiouk** [comment]
I can conifrm, same issues.

**Comment by hinink** [comment]
npm ERR! /root/.cache/node-gyp/16.14.0/include/node/v8.h:3060:44: 附注： 备选需要 1 实参，但提供了 0 个
npm ERR! ../src/validation.cc: 在全局域：
npm ERR! ../src/validation.cc:140:6: 错误：变量或字段‘init’声明为 void
npm ERR!   140 | void init (Handle<Object> target)
npm ERR!       |      ^~~~
npm ERR! ../src/validation.cc:140:12: 错误：‘Handle’在此作用域中尚未声明
npm ERR!   140 | void init (Handle<Object> target)
npm ERR!       |            ^~~~~~
npm ERR! ../src/validation.cc:140:25: 错误：expected primary-expression before ‘>’ token
npm ERR!   140 | void init (Handle<Object> target)
npm ERR!       |                         ^
npm ERR! ../src/validation.cc:140:27: 错误：‘target’在此作用域中尚未声明
npm ERR!   140 | void init (Handle<Object> target)
npm ERR!       |                           ^~~~~~
npm ERR! In file included from ../src/validation.cc:8:
npm ERR! ../src/validation.cc:146:25: 错误：‘init’ was not declared in this scope; did you mean ‘int’?
npm ERR!   146 | NODE_MODULE(validation, init)
npm ERR!       |                         ^~~~
npm ERR! /root/.cache/node-gyp/16.14.0/include/node/node.h:842:36: 附注：in definition of macro ‘NODE_MODULE_X’
npm ERR!   842 |       (node::addon_register_func) (regfunc),                          \
npm ERR!       |                                    ^~~~~~~
npm ERR! ../src/validation.cc:146:1: 附注：in expansion of macro ‘NODE_MODULE’
npm ERR!   146 | NODE_MODULE(validation, init)
npm ERR!       | ^~~~~~~~~~~
npm ERR! ../src/validation.cc: 在函数‘int is_valid_utf8(size_t, char*)’中:
npm ERR! ../src/validation.cc:81:47: 警告：this statement may fall through [-Wimplicit-fallthrough=]
npm ERR!    81 |       case 5 : ch += (uint8_t) value[i++]; ch <<= 6;
npm ERR!       |                                            ~~~^~~~~
npm ERR! ../src/validation.cc:82:7: 附注：here
npm ERR!    82 |       case 4 : ch += (uint8_t) value[i++]; ch <<= 6;
npm ERR!       |       ^~~~
npm ERR! ../src/validation.cc:82:47: 警告：this statement may fall through [-Wimplicit-fallthrough=]
npm ERR!    82 |       case 4 : ch += (uint8_t) value[i++]; ch <<= 6;
npm ERR!       |                                            ~~~^~~~~
npm ERR! ../src/validation.cc:83:7: 附注：here
npm ERR!    83 |       case 3 : ch += (uint8_t) value[i++]; ch <<= 6;
npm ERR!       |       ^~~~
npm ERR! ../src/validation.cc:83:47: 警告：this statement may fall through [-Wimplicit-fallthrough=]
npm ERR!    83 |       case 3 : ch += (uint8_t) value[i++]; ch <<= 6;
npm ERR!       |                                            ~~~^~~~~
npm ERR! ../src/validation.cc:84:7: 附注：here
npm ERR!    84 |       case 2 : ch += (uint8_t) value[i++]; ch <<= 6;
npm ERR!       |       ^~~~
npm ERR! ../src/validation.cc:84:47: 警告：this statement may fall through [-Wimplicit-fallthrough=]
npm ERR!    84 |       case 2 : ch += (uint8_t) value[i++]; ch <<= 6;
npm ERR!       |                                            ~~~^~~~~
npm ERR! ../src/validation.cc:85:7: 附注：here
npm ERR!    85 |       case 1 : ch += (uint8_t) value[i++]; ch <<= 6;
npm ERR!       |       ^~~~
npm ERR! ../src/validation.cc:85:47: 警告：this statement may fall through [-Wimplicit-fallthrough=]
npm ERR!    85 |       case 1 : ch += (uint8_t) value[i++]; ch <<= 6;
npm ERR!       |                                            ~~~^~~~~
npm ERR! ../src/validation.cc:86:7: 附注：here
npm ERR!    86 |       case 0 : ch += (uint8_t) value[i];
npm ERR!       |       ^~~~
npm ERR! ../src/validation.cc: 在函数‘int isLegalUTF8(const uint8_t*, int)’中:
npm ERR! ../src/validation.cc:51:13: 警告：this statement may fall through [-Wimplicit-fallthrough=]
npm ERR!    51 |     case 4: if ((a = (*--srcptr)) < 0x80 || a > 0xBF) return 0;
npm ERR!       |             ^~
npm ERR! ../src/validation.cc:52:5: 附注：here
npm ERR!    52 |     case 3: if ((a = (*--srcptr)) < 0x80 || a > 0xBF) return 0;
npm ERR!       |     ^~~~
npm ERR! ../src/validation.cc:52:13: 警告：this statement may fall through [-Wimplicit-fallthrough=]
npm ERR!    52 |     case 3: if ((a = (*--srcptr)) < 0x80 || a > 0xBF) return 0;
npm ERR!       |             ^~
npm ERR! ../src/validation.cc:53:5: 附注：here
npm ERR!    53 |     case 2: if ((a = (*--srcptr)) < 0x80 || a > 0xBF) return 0;
npm ERR!       |     ^~~~
npm ERR! ../src/validation.cc:54:7: 警告：this statement may fall through [-Wimplicit-fallthrough=]
npm ERR!    54 |       switch (*source) {
npm ERR!       |       ^~~~~~
npm ERR! ../src/validation.cc:62:5: 附注：here
npm ERR!    62 |     case 1: if (*source >= 0x80 && *source < 0xC2) return 0;
npm ERR!       |     ^~~~
npm ERR! make: *** [validation.target.mk:112：Release/obj.target/validation/src/validation.o] 错误 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Linux 5.14.0-119.el9.x86_64
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /var/www/explorer/node_modules/utf-8-validate
npm ERR! gyp ERR! node -v v16.14.0
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-07-29T10_24_31_400Z-debug-0.log
